name: CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Manual deployment environment'
        type: environment
        required: true

jobs:
  deploy-to-staging:
    concurrency:
      group: deploy-staging
      cancel-in-progress: true
    name: Deploy Encapsulate to Staging
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'staging')
    env:
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      # Repository secrets
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
    environment:
      name: staging
      # url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Create SSH key
      #   run: |
      #     mkdir -p ~/.ssh/
      #     echo "${{secrets.EC2_SSH_KEY}}" > ../private.key
      #     sudo chmod 600 ../private.key
      #     ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      #   shell: bash

      - name: Upload repo to EC2
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avz --delete
          path: ./
          remote_path: ~/app
          remote_host: ${{ secrets.EC2_HOST }}
          remote_user: ${{ secrets.EC2_USERNAME }}
          remote_key: ${{ secrets.EC2_SSH_KEY }}
        # run: |
        #   rsync -avz --delete -e "ssh -i ../private.key" \
        #     --exclude '.git' \
        #     --exclude 'node_modules' \
        #     ./ ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/app

      - name: Connect to Server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.PASSWORD }}
          port: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app

            echo "storing secrets"
            echo "DATABASE_URI=${{ secrets.DATABASE_URI }}" >> .env
            echo "PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }}" >> .env

            echo "Stopping old containers"
            docker-compose down
      #   run: |
      #     echo "Connecting via SSH..."

      #     ssh -i ../private.key ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} <<'EOT'
      #     cd ~/app
      #     echo "storing secrets"
      #     echo "DATABASE_URI=${{ secrets.DATABASE_URI }}" >> .env
      #     echo "PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }}" >> .env

      #     echo "Stopping old containers"
      #     docker-compose down

      #     echo "Rebuilding and starting containers"
      #     docker-compose up -d --build
      #     EOT

  deploy-to-production:
    concurrency:
      group: deploy-production
      cancel-in-progress: true
    name: Deploy Encapsulate to Production
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production'
    env:
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      # Repository secrets
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "To be implemented"
      # To be implemented at a later stage
